
authors = [
    "Augustinus Hipponensis",
    "Hieronymus Stridonensis",
    "Walafridus Strabo",
    "Petrus Damianus",
    "Bernardus Claraevallensis",
    "Rabanus Maurus",
    "Beda",
    "Ambrosius Mediolanensis",
    "Alcuinus",
    "Anselmus Cantuariensis",
    "Hugo de S- Victore",
    "Hincmarus Rhemensis",
    "Hildebertus Cenomanensis",
    "Richardus S- Victoris",
    "Tertullianus",
    "Rupertus Tuitiensis",
    "Honorius Augustodunensis",
    "Prosper Aquitanus",
    "Agobardus Lugdunensis",
    "Gregorius I",
    "Marbodus Redonensis",
    "Isidorus Hispalensis",
    "Ratherius Veronensis",
    "Venantius Fortunatus",
    "Boetius",
    "Innocentius III",
    "Petrus Blesensis",
    "Bruno Astensis",
    "Petrus Abaelardus",
    "Philippus de Harveng",
    "Gerhohus Reicherspergensis",
    "Cyprianus Carthaginensis",
    "Hucbaldus S- Amandi",
    "Hrothsuita Gandersheimensis",
    "Hilarius Pictaviensis",
    "Othlonus S- Emmerammi Ratisponensis",
    "Bernaldus Constantiensis",
    "Reinerus S- Laurentii Leodiensis",
    "Alanus de Insulis",
    "Ausonius Burdigalensis",
    "Fulgentius Ruspensis",
    "Guillelmus abbas",
    "Sigebertus Gemblacensis",
    "Petrus Cluniacensis",
    "Ennodius Ticinensis",
    "Berno Augiae Divitis",
    "Paschasius Radbertus",
    "Leo I",
    "Joannes Scotus Erigena",
    "Lactantius"
]
